name: Deploy artifacts

on:
  workflow_run:
    workflows: [ 'Build and test' ]
    branches: [ 'develop', 'master' ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 8 for compiling Java 8 compatible bytecode
        id: setup-java-8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
      - name: Set up Maven Central deployment
        uses: actions/setup-java@v4
        with: # update the settings.xml
          distribution: temurin
          java-version: 11
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Publish to Apache Maven Central
        run: ./mvnw --batch-mode --no-snapshot-updates -Ppublish deploy -DskipTests
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.SONATYPE_USER }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
