name: Release

on:
  push:
    branches: [ 'release/*' ]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Determine version
        id: get_version
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
        shell: bash
        run: |
          source .github/scripts/versioning.sh
          validate_version "${BRANCH##*/}"
          echo "version=${BRANCH##*/}" >> $GITHUB_OUTPUT
      - name: Print version
        id: print_version
        shell: bash
        run: |
          echo "version: ${{ steps.get_version.outputs.version }}"

