name: Release

on:
  push:
    branches: [ 'release/*' ]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Determine version
        id: get_version
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
        shell: bash
        run: |
          if [[ ${BRANCH##*/} =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9\.]+)*(\+[A-Za-z0-9\.\-]+)?$ ]]; then
            echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
            echo "version=${BRANCH##*/}" >> $GITHUB_OUTPUT
          else
            echo "::error::Not a valid version: ${BRANCH##*/}"
            exit 1
          fi
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            8
            11
          mvn-toolchain-id: |
            jdk8
            jdk11
          cache: maven
#      - name: Fetch branch
#        env:
#          BRANCH: ${{ steps.get_version.outputs.branch }}
#        run: |
#          git fetch origin
#          git checkout "${BRANCH}" || git checkout -B "${BRANCH}" "origin/${BRANCH}" && git pull --ff-only && git submodule update --init --recursive
      - name: Set version
        id: set_version
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: ./mvnw --batch-mode versions:set versions:commit -DnewVersion="${VERSION}" -DprocessAllModules=true
      - name: Commit and tag new version
        env:
#          BRANCH: ${{ steps.get_version.outputs.branch }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          git config user.name "Talsma CI"
          git config user.email "ci-user@talsma-ict.nl"
          git commit -sam "Release: Set project version to ${VERSION}"
          git tag -m "Release version ${VERSION}" "${VERSION}"
#          git push --follow-tags
      - name: Set next snapshot version
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          read base minor suffix <<<$(echo "${VERSION}" | perl -pe 's/^(.*?)([0-9]+)([^0-9]*)$/\1 \2 \3/')
          nextSnapshot="${base}$((minor+1))${suffix}-SNAPSHOT"
          ./mvnw --batch-mode versions:set versions:commit -DnewVersion="${nextSnapshot}" -DprocessAllModules=true
          git commit -sam "Release: Set next project version to ${nextSnapshot}"
#          git push --follow-tags
